steps:
  - name: gcr.io/$PROJECT_ID/testrunner
    args:
      - '-c'
      - >
        echo Pulling image dev image with tag $SHORT_SHA ...

        docker pull
        $LOCATION-docker.pkg.dev/$_DEV_PROJECT_ID/$_GAR_DEV_REPO/$_GAR_PACKAGE:$SHORT_SHA

        echo Tagging pulled image as a release candidate $TAG_NAME ...

        docker tag
        $LOCATION-docker.pkg.dev/$_DEV_PROJECT_ID/$_GAR_DEV_REPO/$_GAR_PACKAGE:$SHORT_SHA
        $LOCATION-docker.pkg.dev/$PROJECT_ID/$_GAR_RELEASES_REPO/$_GAR_PACKAGE:$TAG_NAME

        echo Pushing tagged image to release GAR ...

        docker push
        $LOCATION-docker.pkg.dev/$PROJECT_ID/$_GAR_RELEASES_REPO/$_GAR_PACKAGE:$TAG_NAME

        gcloud run deploy survey-assist-api
        --image=$LOCATION-docker.pkg.dev/$PROJECT_ID/$_GAR_RELEASES_REPO/$_GAR_PACKAGE:$TAG_NAME
        --region $LOCATION --project $_PREPROD_PROJECT_ID

        export
        SURVEY_ASSIST_API_URL="https://survey-assist-api-$_PREPROD_PROJECT_NUMBER.$LOCATION.run.app/v1/survey-assist"

        export SA_ID_TOKEN=`gcloud auth print-identity-token
        --impersonate-service-account=$_API_SA`

        echo Running smoke tests against Survey Assit API
        $$SURVEY_ASSIST_API_URL

        pytest cicd
    id: 'Promote release image, Deploy and Run Smoke Tests'
    entrypoint: bash
timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY